CREATE TABLE IF NOT EXISTS tokens (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    hash BYTEA NOT NULL,
    user_id BIGINT REFERENCES users ON DELETE CASCADE,
    expiry TIMESTAMPTZ NOT NULL,
    scope text NOT NULL
);
